### ISSUE TITLE
1.4.4. Verify Installation : openOCD - stlink.cfg does not exist [anymore?]

### ISSUE THREAD

**Issue by cocoacrumbs** [rust-embedded/book#277] opened 2021-01-04 08:40 UTC
The embedded rust book in section 1.4.4 suggests to use this command to verify the installation:

```
openocd -f interface/stlink.cfg -f target/stm32f3x.cfg
```

However, the `stlink.cfg` file does not exist when installing openOCD (which is version 0.10.0 in my case):

```
$ openocd --version
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
```

I found the available interface scripts for openOCD at this path (I'm using Manjaro Linux):

```
/usr/share/openocd/scripts/interface
```

The available stlink scripts are:

```
stlink-v1.cfg
stlink-v2.cfg
stlink-v2-1.cfg
```

In my case, using `stlink-v2-1.cfg` solved my problem.

Maybe the Embedded Rust book could elaborate a bit more on using/finding the correct interface file?

**Comment by mqsoh** [comment] 2021-01-18 18:26
This is a duplicate of #263.

**Closed** 2021-02-17 08:10 UTC
